#itau-up2-action-external-management/.github/actions/peter-murray/workflow-application-token-action/action.yml
name: workflow-application-token-action
description: Obtain a temporary access token for a GitHub Application when running in a GitHub Actions Workflow.
author: peter-murray
inputs:
  application_private_key:
    description: GitHub Application Private Key value.
    required: true
  application_id:
    description: GitHub Application ID value.
    required: true
  permissions:
    description: "The permissions to request e.g. issues:read,secrets:write,packages:read. Defaults to all available permissions"
    required: false
  organization:
    description: The GitHub Organization to get the application installation for, if not specified will use the current repository instead
    required: false
  github_api_base_url:
    description: The GitHub API base URL to use, no needed it working within the same GitHub instance as the workflow as it will get picked up from the environment
    required: false
  https_proxy:
    description: Option proxy server for making the requests
    required: false
  revoke_token:
    description: Flag to revoke the token after the job is complete, defaults to 'false', set to 'true' to revoke in the post job processing.
    required: false
    default: 'false'
outputs:
  token:
    description: "Token generated by the GitHub App."
    value: ${{ steps.github_app.outputs.token }}

runs:
  using: composite
  steps:
    - name: Get Token
      id: github_app
      uses: peter-murray/workflow-application-token-action@v4
      with:
        application_id: ${{ inputs.application_id }}
        application_private_key: ${{ inputs.application_private_key }}
        https_proxy: ${{ inputs.https_proxy }}
        organization: ${{ inputs.organization }}

    # TODO: testar se é possível usar o create-github-app-token

    # - name: Get Token
    #   id: github_app
    #   uses: actions/create-github-app-token@v1
    #   with:
    #     application_id: ${{ inputs.application_id }}
    #     application_private_key: ${{ inputs.application_private_key }}